# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Source shared configuration
if [ -f ~/.shellrc ]; then
  . ~/.shellrc
fi

# Bash-specific prompt
export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\033[38;5;6m\][\w]:\[$(tput sgr0)\]\033[38;5;15m\] \[$(tput sgr0)\]"

# Autojump
[[ -s /usr/share/autojump/autojump.bash ]] && source /usr/share/autojump/autojump.bash