# Load Antidote
source ${HOME}/.antidote/antidote.zsh

# Initialize Antidote
antidote load

# Load Powerlevel10k
source ${HOME}/.antidote/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Source shared configuration
[[ -f ~/.shellrc ]] && source ~/.shellrc

# Autojump
[[ -s /usr/share/autojump/autojump.zsh ]] && source /usr/share/autojump/autojump.zsh

# Set PATH
export PATH="$HOME/.local/bin:$PATH"

# Zsh settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
