name: Pull request check
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Install dependencies
        run: make install-deps

      - name: Generate JSON Schema
        run: make generate-json-schema
