name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Install dependencies
        run: make install-deps

      - name: Generate JSON Schema
        run: make generate-json-schema

      - name: Release generated artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/**/*.json
